### ISSUE TITLE
Multiple concurrent runs overwriting ._longbow_filter_*.bam?

### ISSUE THREAD

**Issue by MVesuviusC** [broadinstitute/longbow#129]
Hi, I'm running multiple samples through longbow at the same time on our compute cluster. When I do this, it seems that longbow filter writes out the `._longbow_filter_*.bam` files for each separate sample to the same file. Is this an issue and is there a way to specify the name of these temporary files? 

Thanks!

**Comment by jonn-smith** [comment]
@MVesuviusC Are you running a combined bam file from multiple samples through one instance of longbow, or are you running many separate instances of Longbow each with its own input file?

Assuming the latter, are you supplying the `-o` and `-x` arguments to `longbow filter`?  If not, you can add them to your invocation to tell it where to put the resulting passing and failing reads.

**Comment by jonn-smith** [comment]
Ah - yeah we've automated our versioning and have made a bunch of updates relatively recently.  It's probably worth updating, but you may want to keep your old version around just in case.  I think everything should be backwards compatible (but a lot of stuff has happened since 0.3.0, so I'm no longer 100% sure).

**Comment by MVesuviusC** [comment]
Sure, I'll grab the latest docker container (Thanks for making that available btw, super useful!)

**Comment by MVesuviusC** [comment]
Ok, using the newer version the `._longbow_filter_*.bam` files don't seem to be produced, so this is a non-issue. Thanks!
