### ISSUE TITLE
Specifying UMI length

### ISSUE THREAD

**Issue by MVesuviusC** [broadinstitute/longbow#131]
Hello, I ran longbow to split up my reads and the UMI length I was expecting was 12, however the output UMIs are all 10bp long. Do I need to specify an alternate model when I run longbow annotate? Or is there an alternate way to specify the UMI length?

Thanks!
Matt

**Comment by jonn-smith** [comment]
Hi @MVesuviusC!  Yes, you'll need to specify a different model with a new UMI length.  It's actually pretty straight-forward and can be done by supplying a `json` file with the model spec to `longbow` in the `--model` argument.

You can start from an existing model and modify it so that you can have the number of bases you need in the UMI.  To do so, run the `model` command with the `-d` flag and model you'd like to start with:

```
longbow model -d mas15v2
```

This will create some files detailing the model.  One of these files is the json spec for the given built-in model (`longbow_model_mas15v2.v2.0.0.spec.json`).

From here you can rename and edit the file.  One quick caveat: make sure you rename the json file *and* change the model name to be your own (the `name` field in the json file).

To change the number of bases in the `UMI` you can just find the section where the UMI is defined and change the `10` to a `12`.  Then just use the new json file wherever you'd use the `--model` / `-m` flag.

**Comment by MVesuviusC** [comment]
Awesome, sounds straight forward. I'll give that a go. Thanks for the help!

**Comment by jonn-smith** [comment]
👍

**Comment by MVesuviusC** [comment]
Yup, that worked great. Thanks again!

**Comment by MVesuviusC** [comment]
Just in case this is useful to someone else down the road. Here are models for 3' 10X libraries with 12bp UMIs and 5' 10X libraries with 12bp UMI sequences.

[3_prime_12bp_UMI.zip](https://github.com/broadinstitute/longbow/files/9394556/3_prime_12bp_UMI.zip)

[5_prime.zip](https://github.com/broadinstitute/longbow/files/9394557/5_prime.zip)
