### ISSUE TITLE
longbow correct consumes very large amount of memory

### ISSUE THREAD

**Issue by sagnikbanerjee15** [broadinstitute/longbow#157]
Hello,

I am using longbow to correct the barcodes but I am constantly running out of memory. I am executing the sample on a system that has 247G of memory. I reduced the number of threads to 10 and also brought down the number of raw reads to 10K but the problem still persists. 

Here is the command I am running.

```
longbow correct --force --output-bam merged_segmented_corrected.bam --barcode-uncorrectable-bam merged_segmented_uncorrectable.bam --allow-list /var/lib/cwl/stgfd2864f9-b944-4a63-bf01-85757c06fad1/3M-february-2018.txt --model mas10threeP --threads 10 /var/lib/cwl/stg5e0294c1-7b30-4699-ad51-408d4fb594dc/merged_segmented.bam
```

I am running 0.5.29 version of longbow since the mas10threeP model was used for the experiment. Also, I am executing the longbow correct after the segment step. Please let me know if I need to do anything differently.

Thank you,
Sagnik.

**Comment by jonn-smith** [comment]
Hi @sagnikbanerjee15.  `Correct` uses a lot of memory by design.  This is the trade-off for having fast levenshtein distance lookups.

The `3'` lookup table that gets generated is on the order of 32Gb.  10 threads would put your ram usage at about 320Gb, which is why you're seeing the problem.  In production we only ever run it with a single thread.  I recommend you use a single thread to run this part of the processing.
