### ISSUE TITLE
Creating an isoseq3 compatible output

### ISSUE THREAD

**Issue by velociroger-pb** [broadinstitute/longbow#79]
Hi guys, just documenting the spec for isoseq3 support

What I did:
[As you know, I've posted the data and processing script here](https://downloads.pacbcloud.com/public/dataset/IsoSeq_sandbox/2021_MAS_share/lib3_JU_AML/)

Basically, I processed the reads with longbow and ran the combined extracted data through `isoseq3 tag`. 
When trying to dedup the reads with `isoseq3 dedup`, it would say `terminate called without an active exception. Aborted`.
Liz says this is because the read group tag is messed up. We have a script to iterate through our bams and change the `RG:Z:` tag so that the read group is constant. We also change the `zm:i:` tag to a unique counter since ZMWs are no longer unique. Unfortunately, this is ridiculously slow and it would be nice to have an `isoseq3` compatible output from `longbow`.

Old tags (after `isoseq3 tag --design 16B-10U-T`):
- ec:f:9.77338
- np:i:8
- rq:f:0.999347
- sn:B:f,13.13,19.2964,4.94478,8.61356
- we:i:2756052
- ws:i:110592
- zm:i:59572499
- YS:f:-5961.52
- RC:i:0
- XQ:Z:44/46,0/0,56/60,48/50,30/32,46/46,0/0,44/60,48/50,30/32,46/46,0/0,58/60,48/50,32/32
- YQ:Z:0.9397
- YN:Z:mas15
- YV:i:1
- YG:i:3
- YK:Z:N
- SG:Z:10x_Adapter:0-22,random:23-698,Poly_A:699-727,3p_Adapter:728-752
- **RG:Z:9e129d4c**
- XC:Z:TCAGGTGCAGGTCGGA
- XM:Z:TCCTGCGCAT
- XA:Z:XC-XM

New tags:
-   XC:Z:TCAGGTGCAGGTCGGA
-   XM:Z:TCCTGCGCAT
-   ic:i:1
-   im:Z:m64013e_211031_055434/1/ccs
-   is:i:1
- it:Z:TCAGGTGCAGGTCGGATCCTGCGCAT
- zm:i:60314
- **RG:Z:e4927d21**

Lmk if you need more info

**Comment by kvg** [comment]
Hi Roger,
  This is now fixed in branch `jts_fixed_length_random_model`. That branch still needs some testing before it is merged into `main`, but in testing, it does seem to do the trick.

  A few important points: we've updated the statistical model to also perform the CBC/UMI annotation, which should make it easier to get fully-annotated reads without needing to run our external CBC/UMI annotation tool or isoseq3. We're not correcting/deduping the reads within Longbow yet, so you'll still need to run isoseq3 dedup.

  Some quality of life improvements: the filter command now takes two arguments for output files: -o (for reads passing filters), and -x (for reads failing filters), which means the filter command can now accept piped input and emit piped output. By default, failing reads are just sent to /dev/null. Also, you no longer need to specify the annotation model to every command; this will be autodetected from the program group written into the BAM header. I've also fixed a minor bug with the internal sharder, which was occasionally running into boundary issues towards the end of files.

  Finally, Longbow doesn't alter read group names. However, IsoSeq3 seems to do so. I'm not certain what the correct behavior here should be:

$ samtools view -H /data/m64013e_211031_055434.hifireads.bam | grep '^@RG' | awk '{ print $2 }'
ID:9e129d4c
# samtools view -H /data/annotated.chunk1.bam | grep '^@RG' | awk '{ print $2 }'
ID:9e129d4c
$ samtools view -H /data/filtered.chunk1.bam | grep '^@RG' | awk '{ print $2 }'
ID:9e129d4c
$ samtools view -H /data/segmented.chunk1.bam | grep '^@RG' | awk '{ print $2 }'
ID:9e129d4c
$ samtools view -H /data/extracted.chunk1.bam | grep '^@RG' | awk '{ print $2 }'
ID:9e129d4c
$ samtools view -H /data/dedup.chunk1.bam | grep '^@RG' | awk '{ print $2 }'
ID:e4927d21

  The following commands will now perform all the processing steps:

```
longbow annotate -f -c 1/300 -t 30 -o annotated.chunk1.bam m64013e_211031_055434.hifireads.bam
longbow filter -f -o filtered.chunk1.bam annotated.chunk1.bam
longbow segment -f -o /data/segmented.chunk1.bam /data/filtered.chunk1.bam
longbow extract -f -o /data/extracted.chunk1.bam /data/segmented.chunk1.bam

# Dedup should really be run on all the merged data, but I've included it here for demonstration purposes
isoseq3 dedup /data/segmented.chunk1.bam /data/dedup.chunk1.bam
```

  Or equivalently:

```
longbow annotate -c 1/300 -t 30 m64013e_211031_055434.hifireads.bam | longbow filter | logbow segment | longbow extract -o /data/extracted.chunk1.bam
isoseq3 dedup /data/segmented.chunk1.bam /data/dedup.chunk1.bam
```

  You can build this branch from source, or if you prefer, I've made a Docker image that already has this branch installed: us.gcr.io/broad-dsp-lrma/lr-longbow:0.4.7-kvg2 .

  Let me know how this works for you.  Jonn and I will finish up the testing for this branch and let you know when its merged into `main`.

**Comment by velociroger-pb** [comment]
Sorry it took me a bit to figure out that the CBC/UMI annotation was part of a different model. I can confirm that the QOL improvements work well, at least in my testing. However, I did run into some problems. I thought it would be cleaner to just do a fresh clone and build from there. Below are the exact steps I took:

```
git clone https://github.com/broadinstitute/longbow.git

cd longbow

git checkout jts_fixed_length_random_model

python3 -mvenv venv
. venv/bin/activate
pip3 install -r dev-requirements.txt
pip3 install -e .
```

I can confirm that this installed correctly because I can see the `mas15v2` model in `src/longbow/utils/model.py`. The annotation seems to run fine without complaining:

```
[INFO 2021-11-29 14:18:28 annotate] Invoked via: longbow annotate -m mas15v2 -c 1/300 -t 16 -o mas_aml_1.ann.bam ../data/m64013e_211031_055434.hifireads.bam
[INFO 2021-11-29 14:18:28 annotate] Running with 16 worker subprocess(es)
[INFO 2021-11-29 14:18:30 annotate] Using mas15v2: The standard MAS-seq 15 array element model.
[INFO 2021-11-29 14:19:04 annotate] Annotating 9643 reads from chunk 1/300 (reads 1-9643)
Progress: 100%|███████████████████████████████████████████████████████| 9643/9643 [10:28<00:00, 15.34 read/s]
[INFO 2021-11-29 14:29:33 annotate] Annotated 9643 reads with 36534 total sections.
[INFO 2021-11-29 14:29:33 annotate] Done. Elapsed time: 665.43s. Overall processing rate: 14.49 reads/s.
```

What's weird is that when I try to filter, the vast majority of reads fail filtering:

```
[INFO 2021-11-29 14:40:05   filter] Invoked via: longbow filter -o mas_aml_1.filt.bam mas_aml_1.ann.bam
[INFO 2021-11-29 14:40:05   filter] Writing reads that conform to the model to: mas_aml_1.filt.bam
[INFO 2021-11-29 14:40:05   filter] Writing reads that do not conform to the model to: /dev/null
Progress: 0 read [00:00, ? read/s][INFO 2021-11-29 14:40:06   filter] Using mas15v2: The standard MAS-seq 15 array element model.
[INFO 2021-11-29 14:40:06   filter] Filtering according to mas15v2 model ordered key adapters: A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P
Progress: 9643 read [00:09, 1000.88 read/s]
[INFO 2021-11-29 14:40:15   filter] Done. Elapsed time: 9.70s.
[INFO 2021-11-29 14:40:15   filter] Total Reads Processed: 9643
[INFO 2021-11-29 14:40:15   filter] # Reads Passing Model Filter: 771 (8.00%)
[INFO 2021-11-29 14:40:15   filter] # Reads Failing Model Filter: 8872 (92.00%)
[INFO 2021-11-29 14:40:15   filter] Total # correctly ordered key adapters in passing reads: 771
[INFO 2021-11-29 14:40:15   filter] Total # correctly ordered key adapters in failing reads: 4881
[INFO 2021-11-29 14:40:15   filter] Avg # correctly ordered key adapters per passing read: 1.0000 [16]
[INFO 2021-11-29 14:40:15   filter] Avg # correctly ordered key adapters per failing read: 0.5502 [16]
```

Curiously, when I run on the normal `mas15` model, I only get a 65% pass rate as opposed to the >99% pass rate with the current main branch. I haven't dug more into the failed reads, but will soon.

**Comment by velociroger-pb** [comment]
After a fresh pull/build this morning and testing on a chunk of 5' data, this seems to be working (~98% pass rate) and `isoseq3 dedup` doesn't complain. Thanks guys!

**Comment by hmyh1202** [comment]
> 

hello  can you share me you code from ccs to downstream steps ?
